### ISSUE TITLE
[실습2] 테스트 케이스 작성 및 결함 찾기

### ISSUE THREAD

**Issue by eunbi-kim** [eunbi-kim/20230831_Creative#2]
[TC양식.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12494189/TC.xlsx)

**Comment by Yjounji** [comment]
[TC_3조.zip](https://github.com/eunbi-kim/20230831_Creative/files/12494432/TC_3.zip)

**Comment by rlaxodnd98** [comment]
[TC4조.zip](https://github.com/eunbi-kim/20230831_Creative/files/12494440/TC4.zip)

**Comment by baesket** [comment]
[TC_2조.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12494570/TC_2.xlsx)

**Comment by aoudrs** [comment]
[TC_6조.zip](https://github.com/eunbi-kim/20230831_Creative/files/12494591/TC_6.zip)

**Comment by JangwookKim0127** [comment]
[TC_5조_0901.zip](https://github.com/eunbi-kim/20230831_Creative/files/12494596/TC_5._0901.zip)

**Comment by abc123abr123** [comment]
[TC_1조.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12494638/TC_1.xlsx)
