### ISSUE TITLE
[실습3] 원격시동 - 테스트 케이스 작성

### ISSUE THREAD

**Issue by eunbi-kim** [eunbi-kim/20230831_Creative#3]
[SW테스트_실습.pdf](https://github.com/eunbi-kim/20230831_Creative/files/12529294/SW._.pdf)
[TC양식.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529295/TC.xlsx)

**Comment by 5riggulggul** [comment]
[스마트키 원격 시동 테스트 케이스 작성_송주영.xls](https://github.com/eunbi-kim/20230831_Creative/files/12529430/_.xls)

**Comment by rlaxodnd98** [comment]
[원격시동_TC.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529445/_TC.zip)

**Comment by suzzzini** [comment]
[스마트키 원격 시동 테스트 케이스 작성_권수진.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529452/_.xlsx)

**Comment by baesket** [comment]
[스마트키 원격 시동 TC_배재영.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529456/TC_.xlsx)

**Comment by ksy14838** [comment]
[원격시동 TC.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529422/TC.zip)

**Comment by JangwookKim0127** [comment]
[스마트키 원격 시동 테스트 케이스 작성_김장욱.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529478/_.xlsx)

**Comment by Yjounji** [comment]
[원격시동 TC_이영준.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529485/TC_.zip)

**Comment by seong-heon** [comment]
[스마트키 원격 시동 테스트 케이스 작성_정성헌.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529489/_.zip)

**Comment by hwa10209** [comment]
[TC_김현준.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529491/TC_.zip)

**Comment by aoudrs** [comment]
[TC_스마트키원격시동_박채연.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529492/TC_._.zip)

**Comment by iparkjoon** [comment]
[TC.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529517/TC.xlsx)

**Comment by gueeun** [comment]
[TC_GE_(1).xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529521/TC_GE_.1.xlsx)

**Comment by S-J-K-I-M** [comment]
[Test Case.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529520/Test.Case.zip)

**Comment by aafunsu** [comment]
[TC_현수종.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529519/TC_.xlsx)

**Comment by kytmt** [comment]
[TC_이건영.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529522/TC_.zip)

**Comment by zmzmalsk** [comment]
[스마트키 원격 시동 테스트 케이스_손신일.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529524/_.zip)

**Comment by castleis** [comment]
[원격시동 TC_김성은.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529525/TC_.zip)

**Comment by choi-bg** [comment]
[최현준_원격시동TC.xlsx](https://github.com/eunbi-kim/20230831_Creative/files/12529592/_.TC.xlsx)

**Comment by ParkJH0902** [comment]
[TC_Assniig.xlsx.zip](https://github.com/eunbi-kim/20230831_Creative/files/12529662/TC_Assniig.xlsx.zip)
